version: '3.8'

services:
  wz-dev-01:
    image: ${CONTAINER_IMAGE}:${CONTAINER_IMAGE_TAG}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./application.properties:/tmp/application.properties
      # Our Code
      - ../../code/is-packages/WzAssert/:${GUEST_IS_HOME}/packages/WzAssert/
      - ../../code/is-packages/WzAssertLocalTest/:${GUEST_IS_HOME}/packages/WzAssertLocalTest/
      - ../../code/is-packages/WzAssertManualTest/:${GUEST_IS_HOME}/packages/WzAssertManualTest/
      - ../../code/is-packages/WzLog/:${GUEST_IS_HOME}/packages/WzLog/
      - ../../code/is-packages/WzLogManualTest/:${GUEST_IS_HOME}/packages/WzLogManualTest/
      - ../../code/is-packages/WzTestManager/:${GUEST_IS_HOME}/packages/WzTestManager/
      - ../../code/is-packages/WzTestManagerManualTest/:${GUEST_IS_HOME}/packages/WzTestManagerManualTest/
      - ../../code/is-packages/WzUtil/:${GUEST_IS_HOME}/packages/WzUtil/
      - ../../code/is-packages/WzUtilLocalTest/:${GUEST_IS_HOME}/packages/WzUtilLocalTest/
      - ../../code/is-packages/WzUtilManualTest/:${GUEST_IS_HOME}/packages/WzUtilManualTest/
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
